### ISSUE TITLE
ADMIN: criar uma tela de cadastrar reserva

### ISSUE THREAD

**Issue by alessandrofeitoza** [alessandrofeitoza/laravel-api-events#22]

**Comment by paulovictordev** [comment]
Essa issue já foi resolvida pela PR https://github.com/alessandrofeitoza/laravel-api-events/pull/37, porém esse commit ebcdcb1b8ddad6c0e4087f206616ce28889b98d1 removeu parte do desenvolvimento. Vou subir novamente o que tá faltando.
